#!/usr/bin/env bash
# Deploys the Expert Dental Studio patient site to the VPS2402 origin (DEC-795).
#
#   bash scripts/raimov/deploy-patient-site.sh              # staging preview
#   bash scripts/raimov/deploy-patient-site.sh production   # expertdental.kg cutover
#
# Run from the canonical workdir on VPS2402. The script builds, gates, publishes to a
# timestamped release directory and flips a symlink, so a rollback is one symlink move
# rather than a re-upload.
set -euo pipefail

HOST_MODE="${1:-staging}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

case "$HOST_MODE" in
  staging)    DOMAIN="clinic.raimovdental.com" ;;
  production) DOMAIN="expertdental.kg" ;;
  *) echo "Usage: $0 [staging|production]" >&2; exit 2 ;;
esac

# Publishing writes release dirs and nginx config straight onto the box, so running it
# anywhere but the origin quietly builds a webroot nobody serves and leaves a vhost that
# breaks the local `nginx -t`. Refuse instead.
ORIGIN_HOST="vps2402"
if [[ "$(hostname -s)" != "$ORIGIN_HOST" ]]; then
  cat >&2 <<EOF
Refusing to deploy: this publishes to the ${DOMAIN} origin and must run on ${ORIGIN_HOST},
but this box is $(hostname -s). Run it on the origin:

  ssh ${ORIGIN_HOST}-root 'cd /var/www/grainee-v2 && git pull --ff-only origin main \\
    && bash scripts/raimov/deploy-patient-site.sh ${HOST_MODE}'
EOF
  exit 2
fi

WEBROOT="/var/www/${DOMAIN}"
RELEASES="${WEBROOT}/releases"
CURRENT="${WEBROOT}/current"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
DIST="${REPO}/site-raimovdental/dist/patient-${HOST_MODE}"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

say "1/7 build"
node "${REPO}/scripts/raimov/build-patient-site.mjs" --host "$HOST_MODE"

say "2/7 quality gates"
node "${REPO}/scripts/raimov/check-patient-site.mjs" --dist "$DIST"

say "3/7 publish release ${STAMP}"
mkdir -p "$RELEASES"
rsync -a --delete "${DIST}/" "${RELEASES}/${STAMP}/"
SOURCE_SHA="$(git -C "$REPO" rev-parse HEAD)"
printf '{"sha":"%s","deployedAt":"%s","host":"%s"}\n' \
  "$SOURCE_SHA" "$STAMP" "$DOMAIN" > "${RELEASES}/${STAMP}/release.json"
ln -sfn "${RELEASES}/${STAMP}" "${CURRENT}.tmp"
mv -Tf "${CURRENT}.tmp" "$CURRENT"
# Keep the five most recent releases; older ones are recoverable from git anyway.
ls -1dt "${RELEASES}"/*/ 2>/dev/null | tail -n +6 | xargs -r rm -rf

say "4/7 nginx config"
install -m 0644 "${REPO}/site-raimovdental/deploy/${DOMAIN}.origin.conf" \
  "/etc/nginx/sites-available/${DOMAIN}.origin.conf"
ln -sfn "/etc/nginx/sites-available/${DOMAIN}.origin.conf" \
  "/etc/nginx/sites-enabled/${DOMAIN}.origin.conf"

# The redirect map is a build artefact; nginx needs it as location blocks.
python3 - "$DIST" "$DOMAIN" <<'PY'
import sys, pathlib
dist, domain = sys.argv[1], sys.argv[2]
src = pathlib.Path(dist, 'redirects.map')
out = ['# Generated by scripts/raimov/build-patient-site.mjs — do not edit by hand.']
for line in src.read_text().splitlines():
    line = line.strip().rstrip(';')
    if not line:
        continue
    frm, to = line.split(' ')
    out.append(f'location = {frm} {{ return 301 {to}; }}')
slug = domain.replace('.', '-').removesuffix('-com').removesuffix('-kg')
pathlib.Path(f'/etc/nginx/snippets/{slug}-redirects.conf').write_text('\n'.join(out) + '\n')
print(f'  {len(out) - 1} redirects -> /etc/nginx/snippets/{slug}-redirects.conf')
PY

say "5/7 nginx test + reload"
nginx -t
systemctl reload nginx
# Reload is asynchronous: old workers keep serving until they drain, and a smoke run
# started immediately can still hit the previous TLS context.
sleep 3

say "6/7 purge edge cache"
# Assets are served with max-age=30d. CSS and JS carry a content hash so a new build is
# a new URL, but images and fonts keep stable names on purpose — without a purge the
# edge keeps serving the previous portraits for a month after they are replaced.
if [[ -f /etc/evo/secrets.env ]]; then
  set -a; . /etc/evo/secrets.env; set +a
fi
if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  ZONE=$(echo "$DOMAIN" | awk -F. '{print $(NF-1)"."$NF}')
  ZONE_ID=$(curl -sS -m 20 -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    "https://api.cloudflare.com/client/v4/zones?name=${ZONE}" |
    python3 -c 'import sys,json; r=json.load(sys.stdin).get("result") or [{}]; print(r[0].get("id",""))')
  if [[ -n "$ZONE_ID" ]]; then
    PURGED=$(curl -sS -m 30 -X POST \
      -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" -H 'Content-Type: application/json' \
      --data "{\"hosts\":[\"${DOMAIN}\"]}" \
      "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache" |
      python3 -c 'import sys,json; print(json.load(sys.stdin).get("success"))')
    echo "  purge ${DOMAIN} (zone ${ZONE}): ${PURGED}"
  else
    echo "  WARN: zone ${ZONE} not found — cache not purged"
  fi
else
  echo "  WARN: CLOUDFLARE_API_TOKEN unset — cache not purged"
fi

say "7/7 smoke"
fails=0
check() {
  local path="$1" expect="$2"
  local code
  code="$(curl -sS -o /dev/null -m 20 -w '%{http_code}' "https://${DOMAIN}${path}")"
  if [[ "$code" == "$expect" ]]; then
    printf '  %-3s %s\n' "$code" "$path"
  else
    printf '  \033[31m%-3s %s (expected %s)\033[0m\n' "$code" "$path" "$expect"
    fails=$((fails + 1))
  fi
}
check /                                   200
check /services/                          200
check /services/gnathology/               200
check /doctors/                           200
check /doctors/raimov-atabek/             200
check /blog/                              200
check /blog/viniry-komu-podhodyat/        200
check /contacts/                          200
check /privacy/                           200
check /sitemap.xml                        200
check /robots.txt                         200
check /release.json                       200
check /services/braces/                   301
check /no-such-page/                      404

if (( fails )); then
  echo
  echo "SMOKE FAILED: ${fails} check(s). Roll back with:" >&2
  echo "  ln -sfn \$(ls -1dt ${RELEASES}/*/ | sed -n 2p) ${CURRENT} && systemctl reload nginx" >&2
  exit 1
fi

echo
echo "deployed ${DOMAIN} -> ${RELEASES}/${STAMP} (sha ${SOURCE_SHA:0:9})"
